services:
  backend:
    networks:
      - default
      - npm

  frontend:
    networks:
      - default
      - npm
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api

networks:
  npm:
    external: true
    name: RED_DE_NPM