# Base de datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.show-sql=false

# Logging
logging.level.org.springframework=WARN
logging.level.org.hibernate.SQL=OFF