# Base de datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.show-sql=false

# Logging
logging.level.mx.gob.sedif.inventarios=WARN
logging.level.org.springframework=WARN
logging.level.org.hibernate.SQL=OFF
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n